# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='test',
  serialized_pb=_b('\n\ntest.proto\x12\x04test\"\"\n\x04Pair\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t\"%\n\x08TestDict\x12\x19\n\x05pairs\x18\x01 \x03(\x0b\x32\n.test.Pair\"1\n\x10\x42unchOfTestDicts\x12\x1d\n\x05\x64icts\x18\x01 \x03(\x0b\x32\x0e.test.TestDict')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PAIR = _descriptor.Descriptor(
  name='Pair',
  full_name='test.Pair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='test.Pair.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='test.Pair.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=54,
)


_TESTDICT = _descriptor.Descriptor(
  name='TestDict',
  full_name='test.TestDict',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pairs', full_name='test.TestDict.pairs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=93,
)


_BUNCHOFTESTDICTS = _descriptor.Descriptor(
  name='BunchOfTestDicts',
  full_name='test.BunchOfTestDicts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dicts', full_name='test.BunchOfTestDicts.dicts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=144,
)

_TESTDICT.fields_by_name['pairs'].message_type = _PAIR
_BUNCHOFTESTDICTS.fields_by_name['dicts'].message_type = _TESTDICT
DESCRIPTOR.message_types_by_name['Pair'] = _PAIR
DESCRIPTOR.message_types_by_name['TestDict'] = _TESTDICT
DESCRIPTOR.message_types_by_name['BunchOfTestDicts'] = _BUNCHOFTESTDICTS

Pair = _reflection.GeneratedProtocolMessageType('Pair', (_message.Message,), dict(
  DESCRIPTOR = _PAIR,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.Pair)
  ))
_sym_db.RegisterMessage(Pair)

TestDict = _reflection.GeneratedProtocolMessageType('TestDict', (_message.Message,), dict(
  DESCRIPTOR = _TESTDICT,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.TestDict)
  ))
_sym_db.RegisterMessage(TestDict)

BunchOfTestDicts = _reflection.GeneratedProtocolMessageType('BunchOfTestDicts', (_message.Message,), dict(
  DESCRIPTOR = _BUNCHOFTESTDICTS,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.BunchOfTestDicts)
  ))
_sym_db.RegisterMessage(BunchOfTestDicts)


# @@protoc_insertion_point(module_scope)
